### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by tumqi** [Leomjson/GTPS-HTTPS#1]
Soo how i can use this for hosting gtps? Or it is even possible?

**Comment by Leomjson** [comment]
@tumqi - This is only to allow a server to be global instead of local.
In short a HTTPS is a way to allow connections through the web, but it doesn't structure the server.

To answer your question, you'd wanna set the HTTPS port to the same port as the ENet port, and also the HTTPS IP to your VPS or VDS IP, you'd also need certificates that specializes your web connection (SSL).

And YES You can host your server with a HTTPS allowing you to play with anyone globally.

**Comment by Publo256** [comment]
What do i need to change at main.cpp?
